### ISSUE TITLE
js文件里能使用么

### ISSUE THREAD

**Issue by shinchanZ** [IFmiss/vue-message#2]

**Comment by AnglerDW** [comment]
@zdd2018 应该是可以的

**Comment by shinchanZ** [comment]
> @zdd2018 应该是可以的

js文件里没法用this指向的，怎么用

**Comment by AnglerDW** [comment]
使用js文件的时候还是需要对应的vue文件的，放在本地项目。在main.JS中引入js文件，再执行初始化 vue.use的操作应该就可以

**Comment by shinchanZ** [comment]
我想在配置api接口的地方用，不会直接调用这个js文件

**Comment by AnglerDW** [comment]
是请求接口提示的时候使用吗？但是你还是要全局引入的啊，在其他地方this.$msg即可

**Comment by shinchanZ** [comment]
统一配置的拦截器里面

**Comment by AnglerDW** [comment]
那你可以在拦截器重新引入Vue执行use  赋值给一个变量 vueInfo  然后执行vueInfo.$msg ，  或者你在main.js中导出实例化的vue对象。然后在里的拦截器文件中引入，再执行$msg就可以了。再执行$msg的时候需要先判断vue.$msg是否存在

**Comment by shinchanZ** [comment]
ooo，懂了，thank u,我试下
